[package]
name = "juju-kubectl"
version = "0.1.0"
authors = ["Kenneth Koski <kennethkoski@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "=3.0.0-beta.2"
juju-rs = { git = "https://github.com/knkski/rust-libjuju.git", rev = "baa1a13" }
structopt = "0.2"
tempfile = "3.1"
